name 'pwx_cookbook'
maintainer 'Ravindra Singh'
maintainer_email 'ravindrasinghkhchi@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures pwx_cookbook'
long_description 'Installs/Configures pwx_cookbook'
version '0.1.3'
chef_version '>= 12.1' if respond_to?(:chef_version)
depends 'ntp'
depends 'docker', '~> 2.0'
